name: Node.js CI

on:
  push:
    branches:
      - main  # Ajoute d'autres branches si nécessaire

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Spécifie la version de Node.js que tu veux utiliser

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
